version: 2.1

orbs:
  terraform: circleci/terraform@3.6.0
  aws-cli: circleci/aws-cli@3.1

jobs:
  plan:
    executor:
      name: aws-cli/default
    parameters:
      aws-access-key-id:
        type: string
        default: ""
      aws-secret-access-key:
        type: string
        default: ""
      aws-region:
        type: string
        default: "us-east-2"  # Change to your desired AWS region
      terraform_workspace:
        type: string
        default: "default"  # Change to your Terraform workspace
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id << parameters.aws-access-key-id >>
            aws configure set aws_secret_access_key << parameters.aws-secret-access-key >>
            aws configure set region << parameters.aws-region >>
      - terraform/install:
          terraform_version: "1.0.2" # Specify your Terraform version
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Select Workspace
          command: terraform workspace select << parameters.terraform_workspace >> || terraform workspace new << parameters.terraform_workspace >>
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan
      - run:
          name: Terraform Show Plan
          command: terraform show -no-color tfplan

  apply:
    executor:
      name: aws-cli/default
    parameters:
      aws-access-key-id:
        type: string
        default: ""
      aws-secret-access-key:
        type: string
        default: ""
      aws-region:
        type: string
        default: "us-east-2" # Change to your desired AWS region
      terraform_workspace:
        type: string
        default: "default"  # Change to your Terraform workspace
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id << parameters.aws-access-key-id >>
            aws configure set aws_secret_access_key << parameters.aws-secret-access-key >>
            aws configure set region << parameters.aws-region >>
      - terraform/install:
          terraform_version: "1.0.2" # Specify your Terraform version
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Select Workspace
          command: terraform workspace select << parameters.terraform_workspace >>
      - run:
          name: Terraform Apply
          command: terraform apply tfplan

workflows:
  terraform_workflow:
    jobs:
      - plan:
          context: aws-credentials # Optional: use a CircleCI context for AWS credentials
          filters:
            branches:
              ignore:
                - main  # Only run on feature branches
      - apply:
          context: aws-credentials # Optional: use a CircleCI context for AWS credentials
          requires:
            - plan
          filters:
            branches:
              only:
                - main  # Only run on the main branch
          aws-access-key-id: $AWS_ACCESS_KEY_ID # Use CircleCI environment variables for security. Do not hardcode!
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY # Use CircleCI environment variables for security. Do not hardcode!
          aws-region: $AWS_REGION # Use CircleCI environment variable
